apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-world-rest-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-rest-api
    spec:
      containers:
      - image: kiranfegade121/hello-world-rest-api:3.0
        imagePullPolicy: IfNotPresent
        name: hello-world-rest-api
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30920
    port: 8080
    targetPort: 8080
  selector:
    app: hello-world-rest-api
  sessionAffinity: None
  type: LoadBalancer
